server:
  port: 8082

spring:
  kafka:
    consumer:
      group-id: console-consumer-1
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


#management:
#  endpoints:
#    web:
#      exposure:
#        include: env,health
#  endpoint:
#    env:
#      enabled: true
#    health:
#      enabled: true
#
#spring:
#  profiles: kafka
#  application:
#    name: demo-receiver
#  main:
#    allow-circular-references: true
#    allow-bean-definition-overriding: true
#  jackson:
#    default-property-inclusion: non_empty
#  cloud:
#    function:
#      definition: inputPayment
#    stream:
#      default-binder: kafka
#      bindings:
#        inputPayment-in-0:
#          content-type: application/json
#          destination: payment_2023
#          group: demo-001
#      kafka:
#        bindings:
#          inputPayment-in-0:
#            consumer:
#              enable-dlq: false
#            binder: kafka
#        binder:
#          configuration:
#            request.timeout.ms: 1000
#            max.block.ms: 3000
#          brokers: localhost
